<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Álbum</title>

    <link href="assets/css/bootstrap.min.css" rel="stylesheet">

    <link href="assets/css/album.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="assets/css/estilo.css">
    <link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">
  </head>

  <body>